In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from NaiveBayes import NaiveBayes

In [2]:
def create_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['label'] = iris.target
    df.columns = [
        'sepal length', 'sepal width', 'petal length', 'petal width', 'label'
    ]
    data = np.array(df.iloc[:100, :])
    return data[:, :-1], data[:, -1]

In [3]:
X, y = create_data()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [4]:
model = NaiveBayes()
model.fit(X_train, y_train)

'NaiveBayes()'

In [5]:
model.predict([4.4, 3.2, 1.3, 0.2])

0.0

In [6]:
model.score(X_test, y_test)

1.0

In [7]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [8]:
model.predict([[4.4, 3.2, 1.3, 0.2]])

array([0.])

In [9]:
model.score(X_test, y_test)

1.0

In [10]:
model = BernoulliNB()
model.fit(X_train, y_train)

BernoulliNB()

In [11]:
model.predict([[4.4, 3.2, 1.3, 0.2]])

array([0.])

In [12]:
model.score(X_test, y_test)

0.4

In [13]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [14]:
model.predict([[4.4, 3.2, 1.3, 0.2]])

array([0.])

In [15]:
model.score(X_test, y_test)

1.0